### PR TITLE
Restructure project to use relative imports and the `__init__.py` convention

### PR DESCRIPTION
**Pull request by ultrabear**
A small but sweeping change to use some more python packaging standards (relative imports, init.py, and main.py), I intentionally did not fix anything that was nonessential to making this work, but this does open the doors for us to further clean stuff up later

### CODE REVIEW

**Comment by ultrabear** [comment]
pytest seems to be failing because it doesn't have a discord bot token to give discord, lol
Im assuming this is a github env secrets thing that my account is not hooked into, idk how that was setup though

**Comment by ultrabear** [comment]
I also moved fetch.py outside of ferris_elf, because it is not a part of the module, its a script

**Comment by ultrabear** [comment]
See comment on ce8cf1f222ca84183629368442a4b7eeb83f732f, idk why we still have `stats.py`

**Comment by ultrabear** [comment]
> pytest seems to be failing because it doesn't have a discord bot token to give discord, lol Im assuming this is a github env secrets thing that my account is not hooked into, idk how that was setup though

Yeah I think this is something that only repo admins can manage, I dont see any options on my end to manage the gh actions secret store, or setup one local to my account

**Comment by proegssilb** [comment]
> > pytest seems to be failing because it doesn't have a discord bot token to give discord, lol Im assuming this is a github env secrets thing that my account is not hooked into, idk how that was setup though
> 
> Yeah I think this is something that only repo admins can manage, I dont see any options on my end to manage the gh actions secret store, or setup one local to my account

It is, but none of our testing should actually require any secrets set up, so I'm not going to populate those env vars just yet. Once we set up integration testing, _then_ we can talk about setting up secrets. But so long as we're just testing individual units of code that shouldn't require the config, we'll have to refactor the code so that it's testable without the config being present.

The sequence I saw in the logs is that `__init__.py` imports `constants.py`, which forces an evaluation of the constants file, which then uses f-strings to build strings from the config at parse time. Reference anything in the config, and then Dynaconf validates the entire config, which then generates the error you saw. This doesn't happen in the current version because the current version of `__init__.py` doesn't need to explicitly import constants.py; python's default behavior was just fine. So then nothing gets evaluated until the test imports `picoseconds.py`, only that one file gets evaluated, and the tests are none the wiser about the shenanigans we do in `constants.py` or anywhere else.

I really don't understand what the goal even was with moving the code from `bot.py` to `__init__.py`. Why?

**Comment by proegssilb** [comment]
As for your question about `stats.py`, if it's broken, we can delete it. We'll need some other tool for monitoring, but we're not quite at that point yet, and I don't have any idea what monitoring we need.

**Comment by ultrabear** [comment]
> I really don't understand what the goal even was with moving the code from bot.py to __init__.py. Why?

It allows us to do relative imports, cutting out a class of unexpectedly-not-in-tree problems, it is also standardized across python

**Comment by proegssilb** [comment]
> It allows us to do relative imports, cutting out a class of unexpectedly-not-in-tree problems, it is also standardized across python

I just grabbed your PR, cut the `__init__.py` code back into `bot.py`, and left `__init__.py` blank. It worked just fine, once I told `main.py` where the `main()` function got moved to. None of the other relative imports had to change. That matches with my understanding that putting code in `__init__.py` is an architectural choice, not a technical requirement.

My last job is skewing my perspective here. There, unit testing required a ton of monkey-patching to isolate units from each other. Having a dozen decorators on a test for all the dependencies that needed to be mocked was common. This is because the code spent a lot of time directly referencing various methods and classes, making a monolithic mess of code. So, absolute imports of modules (not specific methods/classes) and minimizing code in `__init__.py` was the order of the day in order to make that monkey-patching easier; for any given test, you'd only have to patch the source class once, not the imported version everywhere it was being used.

But, I did some quick research, and it seems to be pretty acceptable to either have function/class declarations in `__init__.py` or not. Both approaches seem equally OK (with 5 minutes of googling). I'll have to do some more digging to figure out if there's specific pros/cons that the community has learned, but clearly the situation at my previous job is not universal, regardless of how I feel about declaring functions/classes in __init__.py.

So, absent a technical and conventional reason why classes/methods should/shouldn't be placed in `__init__.py`, I need an architectural reason why the code should/shouldn't go in `__init__.py`.

My thoughts on our architecture:
  - The code base is setup to be fairly monolithic. We don't have clean isolation between anything and Dynaconf, for example. So as we expand unit test coverage, either we're going to have to be judicious in what we test, or we're going to have to spend time monkey-patching to isolate units from each other, and minimize blast radius when someone breaks a unit test.
  - It's not like we can't import from `bot.py` into `__init__.py` for things that really should live in the top-level (I'm not sold I know what those things are just yet, but we can do it). If you put classes and methods directly in `__init__.py`, there it is. You can't alias/import that stuff out of `__init__.py`.
  - Putting all the discord-interacting stuff in `__init__.py` directly feels to me like saying "there's nothing in our codebase that you'd want if you're not going to connect to Discord". Yes, we have a discord bot in our codebase, and that is the main focus of the repo. But we also have a Docker adapter layer, and we're going to have a way to interact with the Advent of Code website too. We have code that builds up a temp dir of stuff. Especially for the sake of testing, there's a lot that our code can do that's worth testing outside of Discord. So quarantine the Discord-interactive stuff in its own file that we can dodge around when we don't want to interact with Discord.
  - We don't have a single `src` folder for all of our code. Instead, we have two: One for the Rust runner inside the container, and another for the bot. So arguing that the `ferris_elf` module is just for the discord bot and nothing else starts to look a bit like a half-truth, due to the amount of supporting code that bot needs in order to function.

But, if there really is a compelling reason that the discord bot code should live in `__init__.py` directly, or that `ferris_elf.bot` shouldn't exist, I'm open to being wrong. Already, I've admitted that my last job is skewing my perspective vs. what the rest of the community finds acceptable. I just need a better argument than "It's conventional".

One more detail, in case it wasn't clear: I've seen some people online argue that using relative imports everywhere like we are is an anti-pattern that makes things messier and harder to test/debug/something. I'm choosing to ignore that for this MR, and wait for whatever the issue is to actually happen before I insist on having an opinion.

**Comment by ultrabear** [comment]
Ah, i didn't know relative imports worked without `__init__.py` present, i thought that was part of the requirements
im fine with not having init.py then, its not perfect but yeah theres alot of this codebase that is cursed by init time things on module load, and we dont have Deref/LazyStatic to smooth anything over, thanks python

**Comment by ultrabear** [comment]
I did actually make a Lazy class but it required callsite changes, or increasingly dynamic hacks, neither of which sounds good for the soul

**Comment by proegssilb** [comment]
> Ah, i didn't know relative imports worked without `__init__.py` present, i thought that was part of the requirements

You have to have the `__init__.py` file. It just doesn't have to contain anything. :)

**Comment by proegssilb** [comment]
> I did actually make a Lazy class but it required callsite changes, or increasingly dynamic hacks, neither of which sounds good for the soul

There really should be a way to do lazy-load constants, Python was way more magic going on in various parts of the language.

You worry about cleaning this up for merge, I'll look into making `constants.py` more lazy.

**Comment by ultrabear** [comment]
> > Ah, i didn't know relative imports worked without `__init__.py` present, i thought that was part of the requirements
> 
> You have to have the `__init__.py` file. It just doesn't have to contain anything. :)

Python Is Really The Language Of All Time

**Review by proegssilb — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
