### PR TITLE
Draft: chore: Update package/python versions

### PR DESCRIPTION
**Pull request by proegssilb**
We talked about python 3.12 on the discord server, so here's a PR that does that.

We probably want a formal/scripted version policy for the following things eventually, but I don't see that as a release blocker:
- Supported Python versions
- Supported Rust versions
- Supported Rust crate versions

### CODE REVIEW

**Comment by proegssilb** [comment]
Note that this code needs testing!!

**Comment by ultrabear** [comment]
reminds me, given that we want reproducable builds we should store the lockfile+toml of each bench, probably using refs to alleviate storage pressure

**Comment by ultrabear** [comment]
Seems like poetry doesnt Just Work on my system, instead it gives me an error that im using py3.11

**Comment by ultrabear** [comment]
Im going to try and use pyenv-virtualenv to get py3.12 for this project

**Comment by ultrabear** [comment]
procedure:
```bash
$ sudo pacman -S pyenv # my distro packages this, dont know if everyone will
$ pyenv install 3.12.1
Downloading Python-3.12.1.tar.xz...
-> https://www.python.org/ftp/python/3.12.1/Python-3.12.1.tar.xz
Installing Python-3.12.1...
Installed Python-3.12.1 to /home/{user}/pyenv/versions/3.12.1

$ poetry env use /home/{user}/.pyenv/versions/3.12.1/bin/python3.12
$ poetry shell
# python is now mapped to 3.12 within the shell, without breaking my system python
```

**Comment by proegssilb** [comment]
@ultrabear Could you try removing pyenv from the setup, and then running `poetry env use 3.12` followed by `poetry run python3 bot.py` ?

Source: https://python-poetry.org/docs/managing-environments/#switching-between-environments

(I personally think there should be a better answer than this, but based on https://stackoverflow.com/questions/60580113/change-python-version-to-3-x , I'm not sure there is)

**Comment by ultrabear** [comment]
> @ultrabear Could you try removing pyenv from the setup, and then running `poetry env use 3.12` followed by `poetry run python3 bot.py` ?
> 
> Source: https://python-poetry.org/docs/managing-environments/#switching-between-environments
> 
> (I personally think there should be a better answer than this, but based on https://stackoverflow.com/questions/60580113/change-python-version-to-3-x , I'm not sure there is)

This doesn't work, because I dont have python3.12 installed on my system without pyenv installing it for me
Heres an example with py3.10
image

**Comment by ultrabear** [comment]
I already tried just doing `poetry env use 3.12` before trying pyenv, poetry does not manage different python versions, which is why i needed pyenv

**Comment by proegssilb** [comment]
OK, that is a shame. Well, I guess let's close this out for now, then, and when we get around to finding a viable alternative for poetry, we can get python 3.12 at the same time.

**Pull request closed without merging**
